from __future__ import annotations

from pathlib import Path

from . import overseas, storage
from .config import DATA_DIR


def _seeded() -> bool:
    flag = DATA_DIR / ".seeded"
    return flag.exists() and (DATA_DIR / "rules.json").exists()


def mark_seeded() -> None:
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    (DATA_DIR / ".seeded").write_text("ok", encoding="utf-8")


def seed_all(force: bool = False) -> dict:
    storage.ensure_data_dir()
    if _seeded() and not force:
        return {"seeded": False, "message": "已有本地数据，跳过初始化"}

    products = [
        {
            "id": "P001",
            "name": "人才盘点与继任",
            "category": "人才发展",
            "desc": "九宫格盘点、高潜识别、继任地图，适配扩张期中高管梯队建设",
        },
        {
            "id": "P002",
            "name": "人才测评（中高管）",
            "category": "测评",
            "desc": "领导力测评、岗位胜任力建模，降低用人风险",
        },
        {
            "id": "P003",
            "name": "组织诊断咨询",
            "category": "OD咨询",
            "desc": "组织架构、权责、协作效率诊断与变革落地陪伴",
        },
        {
            "id": "P004",
            "name": "人事考勤薪酬 SaaS",
            "category": "HR SaaS",
            "desc": "假勤排班、复杂算薪、个税社保一体化",
        },
        {
            "id": "P005",
            "name": "HR一体化 SaaS",
            "category": "HR SaaS",
            "desc": "组织人事+招聘+绩效+假勤薪酬全模块",
        },
        {
            "id": "P006",
            "name": "培训体系与企业大学",
            "category": "学习发展",
            "desc": "课程体系搭建、AI 陪练、管理者训练营",
        },
        {
            "id": "P007",
            "name": "猎头/高管寻访",
            "category": "招聘服务",
            "desc": "关键岗位与高管寻访交付",
        },
        {
            "id": "P008",
            "name": "组织效能与精简咨询",
            "category": "OD咨询",
            "desc": "人效诊断、编制优化、成本可控的组织精简方案",
        },
        {
            "id": "P009",
            "name": "系统迁移与替换方案",
            "category": "实施服务",
            "desc": "从现有 HR 系统平滑迁移、数据清洗与上线陪跑",
        },
        {
            "id": "P010",
            "name": "绩效管理升级",
            "category": "绩效",
            "desc": "OKR/KPI 体系重构、绩效面谈与校准机制",
        },
        {k: v for k, v in overseas.PRODUCT.items()},
    ]

    competitors = [
        {
            "id": "C001",
            "name": "北森",
            "aliases": "Beisen/iTalent/北森云",
            "keywords": "北森/Beisen/iTalentX/熟悉北森",
            "tier": "strong",
            "category": "一体化人才管理",
            "strategy": "强势绑定常见于中大型客户；主打互补（测评深度/OD咨询/细分模块增强），慎推全量替换",
            "enabled": True,
        },
        {
            "id": "C002",
            "name": "i人事",
            "aliases": "利唐/iHR",
            "keywords": "i人事/利唐/ihr360/熟悉i人事",
            "tier": "medium",
            "category": "一体化人事",
            "strategy": "可做模块互补或体验对比，强调实施服务与行业方案",
            "enabled": True,
        },
        {
            "id": "C003",
            "name": "红海云",
            "aliases": "红海eHR",
            "keywords": "红海云/红海eHR/熟悉红海",
            "tier": "strong",
            "category": "集团化/信创 eHR",
            "strategy": "国央企/集团客户常见；推咨询+专项模块，避免正面替换战",
            "enabled": True,
        },
        {
            "id": "C004",
            "name": "薪人薪事",
            "aliases": "薪人薪事HR",
            "keywords": "薪人薪事/熟悉薪人薪事",
            "tier": "medium",
            "category": "中小企业人事",
            "strategy": "规模升级时有替换窗口，主打中大型管理复杂度与人才发展",
            "enabled": True,
        },
        {
            "id": "C005",
            "name": "Moka",
            "aliases": "摩卡招聘",
            "keywords": "Moka/摩卡/熟悉Moka",
            "tier": "medium",
            "category": "招聘 ATS",
            "strategy": "招聘侧已占位；推测评、入职后人才发展与OD，做互补",
            "enabled": True,
        },
        {
            "id": "C006",
            "name": "盖雅工场",
            "aliases": "盖雅",
            "keywords": "盖雅/盖雅工场/劳动力管理",
            "tier": "strong",
            "category": "劳动力/排班",
            "strategy": "蓝领排班强；推白领人才发展、绩效、测评互补",
            "enabled": True,
        },
        {
            "id": "C007",
            "name": "金蝶 s-HR",
            "aliases": "金蝶人事",
            "keywords": "金蝶s-HR/金蝶人事/熟悉金蝶HR",
            "tier": "medium",
            "category": "ERP联动人事",
            "strategy": "财务一体化粘性高；推人才测评盘点与培训等非核心人事模块",
            "enabled": True,
        },
        {
            "id": "C008",
            "name": "用友",
            "aliases": "用友HCM/YonSuite人力",
            "keywords": "用友HCM/用友人事/YonSuite人力",
            "tier": "strong",
            "category": "ERP联动人事",
            "strategy": "类似金蝶，走互补与专项咨询",
            "enabled": True,
        },
        {
            "id": "C009",
            "name": "腾讯乐享",
            "aliases": "乐享",
            "keywords": "腾讯乐享/乐享/企业大学乐享",
            "tier": "medium",
            "category": "学习平台",
            "strategy": "学习平台已有则可推内容体系/测评认证/管理者项目",
            "enabled": True,
        },
        {
            "id": "C010",
            "name": "云学堂",
            "aliases": "",
            "keywords": "云学堂/熟悉云学堂",
            "tier": "medium",
            "category": "学习平台",
            "strategy": "互补内容与组织发展项目",
            "enabled": True,
        },
        {
            "id": "C011",
            "name": "番茄表单/自研打卡",
            "aliases": "钉钉考勤/企业微信打卡/飞书考勤",
            "keywords": "钉钉打卡/企微打卡/飞书打卡/Excel算薪/手工排班/打卡系统难用",
            "tier": "weak",
            "category": "轻量/自研",
            "strategy": "替换窗口明确，主打专业考勤薪酬与合规风险",
            "enabled": True,
        },
        {
            "id": "C012",
            "name": "2号人事部",
            "aliases": "",
            "keywords": "2号人事部/二号人事部",
            "tier": "weak",
            "category": "中小人事",
            "strategy": "成长型企业替换窗口，强调扩展性与人才模块",
            "enabled": True,
        },
        {
            "id": "C013",
            "name": "易路",
            "aliases": "People+",
            "keywords": "易路/People+/熟悉易路",
            "tier": "medium",
            "category": "薪酬劳动力",
            "strategy": "薪酬强；推测评盘点培训互补",
            "enabled": True,
        },
        ]

    scripts = [
        {
            "id": "T001",
            "name": "扩张期·人才盘点开场",
            "signal": "大规模招聘中高层",
            "channel": "电话",
            "body": "您好，我看到贵司最近在招不少管理岗位，是不是团队扩张比较快？我们之前帮几家类似规模的企业做过人才盘点，帮他们在扩张期避免了用错人的坑，想跟您简单聊聊看是否有类似需要。",
            "wechat": "方便加一下微信吗？我把同行业扩张期的人才盘点案例发您看一下，您先了解，不着急。",
            "version": "A",
        },
        {
            "id": "T002",
            "name": "组织变革·OD开场",
            "signal": "招聘HRBP/OD",
            "channel": "电话",
            "body": "您好，注意到贵司在招组织发展/HRBP相关岗位，一般这个阶段组织协作和权责会比较容易卡壳。我们做过不少变革期的组织诊断，想请教一下您这边目前最想先解决的是结构、人效还是干部能力？",
            "wechat": "我把一份组织诊断的轻量清单发您，您可以对照看下哪些点正在发生。",
            "version": "A",
        },
        {
            "id": "T003",
            "name": "考勤薪酬系统开场",
            "signal": "招聘薪酬绩效/考勤",
            "channel": "电话",
            "body": "您好，看到贵司在招薪酬绩效或考勤相关同事，很多企业这个阶段是算薪规则变复杂、手工对账很吃力。想跟您确认下，目前是系统能力不够，还是编制上缺人？我们有一套更适配成长型企业的假勤薪酬方案，可以先做个免费诊断。",
            "wechat": "加个微信，我发一份「算薪容易出错的12个点」清单，您对照自查就行。",
            "version": "A",
        },
        {
            "id": "T004",
            "name": "数字化转型开场",
            "signal": "招聘数字化HR",
            "channel": "电话",
            "body": "您好，贵司在招数字化/信息化相关的HR岗位，说明一体化和数据打通已经被提上日程。我们服务过多家从多套工具迁到一体化平台的企业，想了解下您现在最头疼的是数据孤岛、员工体验，还是管理层要报表？",
            "wechat": "发您一份HR数字化路径图（招聘-假勤-薪酬-绩效），方便对齐内部讨论。",
            "version": "A",
        },
        {
            "id": "T005",
            "name": "培训体系开场",
            "signal": "招聘培训经理",
            "channel": "电话",
            "body": "您好，看到贵司在招培训经理/企业大学相关角色，通常意味着课程体系和管理者培养要正规化。我们既做体系搭建也做AI陪练落地，想请教下您更优先解决的是新人培养、还是中层带队伍？",
            "wechat": "发您一个同行业管理者训练营大纲，您看看是否贴近现状。",
            "version": "A",
        },
        {
            "id": "T006",
            "name": "高管变动开场",
            "signal": "高管变动频繁",
            "channel": "电话",
            "body": "您好，近期待招和公开信息里看到管理层变动比较频繁。很多企业这个阶段会先稳住关键岗位，再做干部标准。我们在高管寻访和领导力测评上有成熟打法，想听听您现在最急的是补人，还是先把标准立住？",
            "wechat": "加微信发您一份「关键岗位画像」模板，方便内部对齐。",
            "version": "A",
        },
        {
            "id": "T007",
            "name": "融资上市开场",
            "signal": "融资/上市",
            "channel": "电话",
            "body": "您好，恭喜贵司到了新的资本阶段。融资/上市前后组织规模化管理压力会陡增——编制、绩效、合规、干部梯队往往会一起冒出来。我们有综合HR解决方案，想先问一句：您内部现在最优先的是哪一块？",
            "wechat": "发您「融资后90天HR待办」清单，方便您和老板对齐优先级。",
            "version": "A",
        },
        {
            "id": "T008",
            "name": "竞品吐槽·替换开场",
            "signal": "员工吐槽考勤系统",
            "channel": "电话",
            "body": "您好，我们注意到不少同行反馈现有考勤/人事系统效率一般，续约前其实是很好的优化窗口。想跟您了解下贵司目前用的系统情况，看是否有可优化的空间——第一次沟通只做需求确认，不推销具体产品。",
            "wechat": "方便加微信吗？我把替换迁移的注意事项发您，您先留着对比。",
            "version": "A",
        },
        {
            "id": "T009",
            "name": "收缩精简开场",
            "signal": "裁员/收缩",
            "channel": "电话",
            "body": "您好，看到行业里有收缩相关动态。这个阶段很多CHRO更关心人效和编制结构是否健康，而不是再上新系统。我们有组织效能诊断，能帮您快速看清哪里能优化、哪里不能动，想请教下您现在是否在做这方面的复盘？",
            "wechat": "发您一份人效诊断框架，偏内部讨论用，不对外传播。",
            "version": "A",
        },
        {
            "id": "T010",
            "name": "通用加微信",
            "signal": "通用",
            "channel": "微信",
            "body": "方便加一下微信吗？我把我们之前给同行业企业做的案例发您看一下，您也可以先了解，不着急，有需要再聊。",
            "wechat": "方便加一下微信吗？我把我们之前给同行业企业做的案例发您看一下，您也可以先了解，不着急，有需要再聊。",
            "version": "A",
        },
        {
            "id": "T011",
            "name": "考勤薪酬开场 B版",
            "signal": "招聘薪酬绩效/考勤",
            "channel": "电话",
            "body": "您好，我是做HR数字化的。看到贵司在扩充薪酬/假勤相关编制，很多团队其实不是缺人，而是规则一复杂系统就撑不住。您方便说下现在算薪大概几套规则吗？我帮您判断是该加人还是该换工具。",
            "wechat": "加个微信，我发对比表（轻量工具 vs 专业薪酬）给您内部讨论。",
            "version": "B",
        },
        *[dict(s) for s in overseas.SCRIPTS],
    ]

    rules = [
        {
            "id": "R001",
            "signal_type": "招聘JD",
            "signal_keywords": "总监/高级经理/VP/副总裁/中层管理/储备干部",
            "signal_strength": 4,
            "need": "组织快速扩张，人才梯队不足",
            "products": "人才盘点、人才测评",
            "confidence": 72,
            "extra_condition": "同时有「融资」新闻则置信度+15",
            "exception": "若仅为校招生管培，不代表中高管梯队缺口",
            "script_id": "T001",
            "author": "系统初版",
            "validation_status": "验证中",
            "hit_count": 0,
            "deal_count": 0,
            "accuracy": 0,
            "enabled": True,
        },
        {
            "id": "R002",
            "signal_type": "招聘JD",
            "signal_keywords": "HRBP/组织发展/OD专员/OD经理/组织效能",
            "signal_strength": 5,
            "need": "组织架构调整/变革期",
            "products": "组织诊断咨询",
            "confidence": 78,
            "extra_condition": "同时有「组织架构调整」则置信度+12",
            "exception": "若是集团下属新设子公司走流程招人，不一定有预算",
            "script_id": "T002",
            "author": "系统初版",
            "validation_status": "验证中",
            "hit_count": 0,
            "deal_count": 0,
            "accuracy": 0,
            "enabled": True,
        },
        {
            "id": "R003",
            "signal_type": "招聘JD",
            "signal_keywords": "薪酬绩效专员/薪酬经理/考勤专员/假勤/算薪/HRIS专员",
            "signal_strength": 5,
            "need": "现有系统效率低或缺失",
            "products": "人事考勤薪酬 SaaS、系统迁移方案",
            "confidence": 80,
            "extra_condition": "同时出现「HRIS」与「薪酬」则置信度+10",
            "exception": "公司规模低于50人，可能只是想省手工做表的HR，预算有限",
            "script_id": "T003",
            "author": "系统初版",
            "validation_status": "已验证有效",
            "hit_count": 0,
            "deal_count": 0,
            "accuracy": 0,
            "enabled": True,
        },
        {
            "id": "R004",
            "signal_type": "招聘JD",
            "signal_keywords": "HR数字化/信息化/HRSSC/共享服务/People Analytics/人力资源系统",
            "signal_strength": 4,
            "need": "HR数字化转型意愿",
            "products": "HR一体化 SaaS整体解决方案",
            "confidence": 75,
            "extra_condition": "同时有「上线」或「选型」则置信度+10",
            "exception": "若JD明确要求维护现有北森/SAP，可能是运维岗而非新购",
            "script_id": "T004",
            "author": "系统初版",
            "validation_status": "验证中",
            "hit_count": 0,
            "deal_count": 0,
            "accuracy": 0,
            "enabled": True,
        },
        {
            "id": "R005",
            "signal_type": "招聘JD",
            "signal_keywords": "培训经理/企业大学/学习发展/L&D/培训体系/人才培养",
            "signal_strength": 4,
            "need": "培训体系建设需求",
            "products": "培训项目、AI课程、企业大学",
            "confidence": 70,
            "extra_condition": "同时有「管理者培养」则置信度+10",
            "exception": "纯销售产品培训岗，不等于企业大学建设",
            "script_id": "T005",
            "author": "系统初版",
            "validation_status": "验证中",
            "hit_count": 0,
            "deal_count": 0,
            "accuracy": 0,
            "enabled": True,
        },
        {
            "id": "R006",
            "signal_type": "企业新闻",
            "signal_keywords": "高管离职/人事震动/管理层调整/CEO更换/空降",
            "signal_strength": 4,
            "need": "组织不稳定/管理层信任与标准问题",
            "products": "猎头服务、高管测评",
            "confidence": 68,
            "extra_condition": "同时招聘「总经理」或「副总裁」则置信度+15",
            "exception": "正常退休交接不代表危机",
            "script_id": "T006",
            "author": "系统初版",
            "validation_status": "验证中",
            "hit_count": 0,
            "deal_count": 0,
            "accuracy": 0,
            "enabled": True,
        },
        {
            "id": "R007",
            "signal_type": "企业新闻",
            "signal_keywords": "融资/A轮/B轮/C轮/IPO/上市/战略投资",
            "signal_strength": 5,
            "need": "组织规模化管理需求激增",
            "products": "综合HR解决方案（全套）",
            "confidence": 82,
            "extra_condition": "同时大规模招聘则置信度+10",
            "exception": "仅战略少数股权投资且业务无扩张，需求可能不强",
            "script_id": "T007",
            "author": "系统初版",
            "validation_status": "已验证有效",
            "hit_count": 0,
            "deal_count": 0,
            "accuracy": 0,
            "enabled": True,
        },
        {
            "id": "R008",
            "signal_type": "员工评价",
            "signal_keywords": "打卡系统难用/考勤坑/算薪错误/工资算错/系统卡/请假麻烦",
            "signal_strength": 5,
            "need": "现有竞品体验差，替换窗口期",
            "products": "系统迁移方案、人事考勤薪酬 SaaS",
            "confidence": 77,
            "extra_condition": "同时提到具体竞品名则置信度+8",
            "exception": "个别门店吐槽不等于总部有采购权",
            "script_id": "T008",
            "author": "系统初版",
            "validation_status": "验证中",
            "hit_count": 0,
            "deal_count": 0,
            "accuracy": 0,
            "enabled": True,
        },
        {
            "id": "R009",
            "signal_type": "行业新闻",
            "signal_keywords": "裁员/优化/收缩/关停并转/降本增效",
            "signal_strength": 4,
            "need": "组织优化、成本控制需求",
            "products": "组织效能诊断、精简咨询",
            "confidence": 74,
            "extra_condition": "同时有「人效」相关表述则置信度+10",
            "exception": "已完成大规模优化且冻结预算时，短期难成交",
            "script_id": "T009",
            "author": "系统初版",
            "validation_status": "验证中",
            "hit_count": 0,
            "deal_count": 0,
            "accuracy": 0,
            "enabled": True,
        },
        {
            "id": "R010",
            "signal_type": "招聘JD",
            "signal_keywords": "熟悉北森/熟悉i人事/熟悉红海/熟悉SAP SuccessFactors/熟悉Workday",
            "signal_strength": 3,
            "need": "已有供应商，需判断替换或互补",
            "products": "互补方案或替换方案（视竞品强弱）",
            "confidence": 65,
            "extra_condition": "员工评价吐槽则置信度+20",
            "exception": "仅要求「了解即可」可能不是深度用户",
            "script_id": "T008",
            "author": "系统初版",
            "validation_status": "验证中",
            "hit_count": 0,
            "deal_count": 0,
            "accuracy": 0,
            "enabled": True,
        },
        {
            "id": "R011",
            "signal_type": "招聘JD",
            "signal_keywords": "绩效经理/OKR/绩效考核/绩效体系/目标管理",
            "signal_strength": 4,
            "need": "绩效管理升级",
            "products": "绩效管理升级、人才盘点",
            "confidence": 71,
            "extra_condition": "同时有组织发展岗位则置信度+10",
            "exception": "纯执行型绩效专员且无体系关键词，需求偏弱",
            "script_id": "T002",
            "author": "系统初版",
            "validation_status": "验证中",
            "hit_count": 0,
            "deal_count": 0,
            "accuracy": 0,
            "enabled": True,
        },
        {
            "id": "R012",
            "signal_type": "招聘JD",
            "signal_keywords": "SSC/共享中心/人事共享/员工关系经理",
            "signal_strength": 3,
            "need": "标准化与共享服务建设",
            "products": "HR一体化 SaaS、组织诊断",
            "confidence": 63,
            "extra_condition": "多地分子公司则置信度+12",
            "exception": "外包客服型SSC与HRSSC不同",
            "script_id": "T004",
            "author": "系统初版",
            "validation_status": "未验证",
            "hit_count": 0,
            "deal_count": 0,
            "accuracy": 0,
            "enabled": True,
        },
        {
            "id": "R013",
            "signal_type": "领英/脉脉",
            "signal_keywords": "新上任HRD/新任CHO/刚入职人力资源总监/到任三个月",
            "signal_strength": 5,
            "need": "新官上任变革窗口",
            "products": "组织诊断、综合HR解决方案",
            "confidence": 76,
            "extra_condition": "同时有融资或扩张新闻则置信度+12",
            "exception": "空降但公司明确冻结变革时窗口短",
            "script_id": "T007",
            "author": "系统初版",
            "validation_status": "验证中",
            "hit_count": 0,
            "deal_count": 0,
            "accuracy": 0,
            "enabled": True,
        },
        {
            "id": "R014",
            "signal_type": "招聘JD",
            "signal_keywords": "Excel算薪/手工考勤/对接钉钉/多套工资规则",
            "signal_strength": 5,
            "need": "从手工/轻量工具升级专业系统",
            "products": "人事考勤薪酬 SaaS",
            "confidence": 84,
            "extra_condition": "人数超过200则置信度+10",
            "exception": "低于50人且创始人亲算薪，付费意愿低",
            "script_id": "T003",
            "author": "系统初版",
            "validation_status": "已验证有效",
            "hit_count": 0,
            "deal_count": 0,
            "accuracy": 0,
            "enabled": True,
        },
        {
            "id": "R015",
            "signal_type": "企业新闻",
            "signal_keywords": "并购/收购收购/收购重组/并表",
            "signal_strength": 5,
            "need": "组织整合、编制与文化融合",
            "products": "组织诊断咨询、人才盘点、一体化SaaS",
            "confidence": 80,
            "extra_condition": "跨地域整合则置信度+8",
            "exception": "财务投资型并购不介入经营时需求弱",
            "script_id": "T002",
            "author": "系统初版",
            "validation_status": "验证中",
            "hit_count": 0,
            "deal_count": 0,
            "accuracy": 0,
            "enabled": True,
        },
        {
            "id": "R016",
            "signal_type": "公开招标",
            "signal_keywords": "人力资源系统采购/eHR招标/考勤系统招标/人事系统立项",
            "signal_strength": 5,
            "need": "明确采购意向",
            "products": "HR一体化 SaaS、实施服务",
            "confidence": 90,
            "extra_condition": "",
            "exception": "仅维保续费招标不是新购",
            "script_id": "T004",
            "author": "系统初版",
            "validation_status": "已验证有效",
            "hit_count": 0,
            "deal_count": 0,
            "accuracy": 0,
            "enabled": True,
        },
        {
            "id": "R017",
            "signal_type": "招聘JD",
            "signal_keywords": "校园招聘经理/校招负责人/管培生",
            "signal_strength": 3,
            "need": "校招与管培体系",
            "products": "人才测评、培训体系",
            "confidence": 60,
            "extra_condition": "管培生规模大则置信度+10",
            "exception": "单次活动型校招执行岗需求弱",
            "script_id": "T005",
            "author": "系统初版",
            "validation_status": "未验证",
            "hit_count": 0,
            "deal_count": 0,
            "accuracy": 0,
            "enabled": True,
        },
        {
            "id": "R018",
            "signal_type": "员工评价",
            "signal_keywords": "绩效不透明/打卡恶心/HR不作为/晋升不公",
            "signal_strength": 3,
            "need": "员工体验与绩效公平性",
            "products": "绩效管理升级、组织诊断",
            "confidence": 58,
            "extra_condition": "多条相似评价则置信度+15",
            "exception": "竞品抹黑或个例情绪宣泄",
            "script_id": "T002",
            "author": "系统初版",
            "validation_status": "未验证",
            "hit_count": 0,
            "deal_count": 0,
            "accuracy": 0,
            "enabled": True,
        },
        {
            "id": "R019",
            "signal_type": "招聘JD",
            "signal_keywords": "薪酬绩效专员/HRIS专员",
            "signal_strength": 5,
            "need": "换考勤/薪酬系统概率高",
            "products": "人事考勤薪酬 SaaS、系统迁移方案",
            "confidence": 85,
            "extra_condition": "同时挂着两岗位则置信度+10",
            "exception": "公司规模低于50人，大概率只想省手工HR，难有SaaS预算",
            "script_id": "T011",
            "author": "系统初版",
            "validation_status": "已验证有效",
            "hit_count": 0,
            "deal_count": 0,
            "accuracy": 0,
            "enabled": True,
        },
        {
            "id": "R020",
            "signal_type": "官网/公众号",
            "signal_keywords": "数字化转型/智慧人力/人才战略/组织能力升级",
            "signal_strength": 3,
            "need": "有数字化叙事，需验证是否真立项",
            "products": "HR一体化 SaaS、组织诊断",
            "confidence": 55,
            "extra_condition": "同时有招标或数字化岗位则置信度+25",
            "exception": "纯品牌宣传无编制/预算信号",
            "script_id": "T004",
            "author": "系统初版",
            "validation_status": "未验证",
            "hit_count": 0,
            "deal_count": 0,
            "accuracy": 0,
            "enabled": True,
        },
        {
            "id": "R021",
            "signal_type": "招聘JD",
            "signal_keywords": "排班/劳动力/门店人力/蓝领考勤",
            "signal_strength": 4,
            "need": "复杂排班与劳动力管理",
            "products": "人事考勤薪酬 SaaS（或与盖雅场景互补的白领方案）",
            "confidence": 69,
            "extra_condition": "零售/餐饮/制造行业则置信度+10",
            "exception": "已深度使用盖雅且续约稳定，替换难",
            "script_id": "T003",
            "author": "系统初版",
            "validation_status": "验证中",
            "hit_count": 0,
            "deal_count": 0,
            "accuracy": 0,
            "enabled": True,
        },
        {
            "id": "R022",
            "signal_type": "企业新闻",
            "signal_keywords": overseas.R022_PATCH["signal_keywords"],
            "signal_strength": 3,
            "need": overseas.R022_PATCH["need"],
            "products": overseas.R022_PATCH["products"],
            "confidence": overseas.R022_PATCH["confidence"],
            "extra_condition": overseas.R022_PATCH["extra_condition"],
            "exception": overseas.R022_PATCH["exception"],
            "script_id": overseas.R022_PATCH["script_id"],
            "author": "系统初版",
            "validation_status": overseas.R022_PATCH["validation_status"],
            "hit_count": 0,
            "deal_count": 0,
            "accuracy": 0,
            "enabled": True,
        },
        *[dict(r) for r in overseas.RULES],
    ]

    now = storage.now_iso()
    for collection, rows in (
        ("products", products),
        ("competitors", competitors),
        ("scripts", scripts),
        ("rules", rules),
    ):
        for row in rows:
            row.setdefault("created_at", now)
            row.setdefault("updated_at", now)
        storage.write_collection(collection, rows)

    scoring = {
        "weights": {
            "urgency": 0.30,
            "budget": 0.25,
            "decision": 0.20,
            "competitor_window": 0.15,
            "industry_fit": 0.10,
        },
        "preferred_industries": ["互联网", "制造", "零售", "消费", "金融", "医药", "教育", "汽车"],
        "followup_cadence_days": [0, 3, 7, 14, 30],
        "updated_at": now,
    }
    storage.write_object("scoring", scoring)

    settings = {
        "brand_name": "肯耐珂萨 · 销售陌拜工作台",
        "brand_tagline": "触达客户 · 挖掘需求 · 建立联系 · 促成交",
        "author": "Ira",
        "org": "肯耐珂萨",
        "compliance_note": "请确保名单来源合法，遵守外呼时段与平台规范。",
        "updated_at": now,
    }
    storage.write_object("settings", settings)

    # 示例线索 + 画像（可演示全流程）
    leads = [
        {
            "id": "L001",
            "name": "王",
            "phone": "13800001001",
            "company": "星澜智造科技",
            "title": "人力资源总监",
            "industry": "智能制造",
            "company_size": "800人",
            "source": "展会名片",
            "notes": "展会认识，提到今年要上统一人事系统",
            "status": "待分析",
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": "L002",
            "name": "李",
            "phone": "13900002002",
            "company": "果味零售集团",
            "title": "HRBP负责人",
            "industry": "零售",
            "company_size": "2000人",
            "source": "脉脉",
            "notes": "新上任三个月，门店排班投诉多",
            "status": "待分析",
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": "L003",
            "name": "陈",
            "phone": "13700003003",
            "company": "云启软件",
            "title": "CHO",
            "industry": "互联网",
            "company_size": "350人",
            "source": "融资新闻跟进",
            "notes": "刚完成B轮",
            "status": "待分析",
            "created_at": now,
            "updated_at": now,
        },
    ]
    storage.write_collection("leads", leads)

    profiles = [
        {
            "id": "PF001",
            "lead_id": "L001",
            "company": "星澜智造科技",
            "industry": "智能制造",
            "company_size": "800人",
            "stage": "扩张期",
            "financing": "A轮后稳健经营",
            "summary": "华东制造企业，多工厂，正在招薪酬绩效专员与HRIS专员，JD提到熟悉北森更好，同时员工评价有「算薪错误」「打卡系统难用」。",
            "jobs": [
                {"title": "薪酬绩效专员", "desc": "负责多工厂算薪规则，熟悉Excel算薪，有HRIS专员协作经验优先，熟悉北森尤佳"},
                {"title": "HRIS专员", "desc": "维护人力资源系统，对接钉钉打卡，推进数字化"},
                {"title": "生产总监", "desc": "新建工厂管理层招聘"},
            ],
            "recruiting_text": "在招：薪酬绩效专员、HRIS专员、生产总监。要求熟悉北森、Excel算薪、对接钉钉。",
            "news_text": "去年新建华南工厂，管理层出现空降生产副总裁。",
            "review_text": "看准网：打卡系统难用；工资算错过；请假麻烦。",
            "website_text": "官网提到数字化转型与智慧工厂。",
            "contact_title": "人力资源总监",
            "contact_notes": "任职约2年",
            "recent_change": True,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": "PF002",
            "lead_id": "L002",
            "company": "果味零售集团",
            "industry": "零售",
            "company_size": "2000人",
            "stage": "门店扩张",
            "financing": "未披露",
            "summary": "连锁零售，新上任HRBP负责人，大量门店排班与蓝领考勤，员工吐槽排班混乱，在招组织发展经理与培训经理。",
            "jobs": [
                {"title": "组织发展经理", "desc": "门店组织效能、OD专员协作"},
                {"title": "培训经理", "desc": "门店培训体系、学习发展"},
                {"title": "排班专员", "desc": "门店人力排班、劳动力管理"},
            ],
            "recruiting_text": "招聘组织发展经理、培训经理、排班专员，强调门店人力与蓝领考勤。",
            "news_text": "今年计划新开80家社区店。",
            "review_text": "排班混乱；加班打卡坑；HR不作为。",
            "website_text": "公众号强调组织能力升级。",
            "contact_title": "HRBP负责人",
            "contact_notes": "新上任HRD风格，到任三个月，脉脉动态活跃",
            "recent_change": True,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": "PF003",
            "lead_id": "L003",
            "company": "云启软件",
            "industry": "互联网",
            "company_size": "350人",
            "stage": "B轮扩张",
            "financing": "B轮",
            "summary": "SaaS公司刚完成B轮融资，大规模招聘中高层与HRBP，公开表示要建人才梯队和企业大学。",
            "jobs": [
                {"title": "研发总监", "desc": "中层管理，带30人团队"},
                {"title": "HRBP", "desc": "业务伙伴，支持组织发展"},
                {"title": "企业大学负责人", "desc": "培训体系与人才培养"},
            ],
            "recruiting_text": "大规模招聘中高层：研发总监、销售总监；同时招HRBP、企业大学负责人、培训经理。",
            "news_text": "完成B轮融资，宣布组织规模化与人才战略。",
            "review_text": "节奏快；晋升不透明。",
            "website_text": "人才战略、组织能力升级。",
            "contact_title": "CHO",
            "contact_notes": "融资后公开访谈提到要建干部梯队",
            "recent_change": True,
            "created_at": now,
            "updated_at": now,
        },
    ]
    storage.write_collection("profiles", profiles)
    storage.write_collection("outreach", [])
    storage.write_collection("followups", [])
    storage.write_collection("wechat_todos", [])

    mark_seeded()
    return {
        "seeded": True,
        "counts": {
            "products": len(products),
            "competitors": len(competitors),
            "scripts": len(scripts),
            "rules": len(rules),
            "leads": len(leads),
            "profiles": len(profiles),
        },
    }


def reset_and_seed() -> dict:
    for name in storage.COLLECTIONS:
        path = Path(storage._path(name))
        if path.exists():
            path.unlink()
    flag = DATA_DIR / ".seeded"
    if flag.exists():
        flag.unlink()
    return seed_all(force=True)
